from __future__ import annotations

import re


def slugify(name: str) -> str:
    cleaned = re.sub(r"[^a-z0-9_]+", "_", (name or "insight_model").lower()).strip("_")
    return cleaned or "insight_model"


def build_dbt_model(
    model_name: str,
    sql: str,
    description: str = "",
    columns: list[str] | None = None,
) -> dict[str, str]:
    """Generate a production-ready dbt model: <name>.sql + schema.yml with tests."""
    slug = slugify(model_name)
    header = (
        "{{ config(materialized='view', tags=['insight']) }}\n"
        f"-- Generated by Insight{' — ' + description if description else ''}\n"
        "-- Review column tests in schema.yml before merging.\n\n"
    )
    model_sql = f"{header}{sql.strip().rstrip(';')};\n"

    column_docs = ""
    for col in columns or []:
        column_docs += (
            f"      - name: {col}\n"
            "        description: ''\n"
            "        data_tests: [not_null]\n"
        )
    schema_yml = (
        "version: 2\n\n"
        "models:\n"
        f"  - name: {slug}\n"
        f"    description: {description or 'Generated by Insight.'}\n"
        "    meta:\n"
        "      generated_by: insight\n"
        "    columns:\n"
        + (column_docs or "      # no columns captured — document them here\n")
    )
    return {
        f"models/{slug}/{slug}.sql": model_sql,
        f"models/{slug}/schema.yml": schema_yml,
        "README.md": (
            f"# {slug} (generated by Insight)\n\n"
            "1. Copy `models/{slug}/` into your dbt project.\n"
            "2. `dbt parse` then adjust materialization/tests.\n"
            "3. The view assumes source tables named exactly as referenced.\n"
        ),
    }


def build_alert_monitor(
    monitor_name: str,
    sql: str,
    question: str = "",
    schedule_cron: str = "0 * * * *",
) -> dict:
    """Generate an anomaly-monitor descriptor ready for a Slack/webhook runner."""
    slug = slugify(monitor_name)
    return {
        "name": slug,
        "source": {"tool": "insight", "question": question},
        "schedule_cron": schedule_cron,
        "query": sql.strip().rstrip(";") + ";",
        "engine": "duckdb",
        "threshold": {"metric_column": None, "op": ">", "value": None},
        "webhook": {
            "url_env": "INSIGHT_ALERT_WEBHOOK_URL",
            "payload_template": {
                "text": (
                    "[Insight] {{ monitor_name }} returned {{ rows }} rows "
                    "(threshold {{ threshold }})"
                )
            },
            "slack_compatible": True,
        },
    }
